# Generated by Django 3.0.3 on 2020-03-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('phoneNo', models.IntegerField(unique=True)),
            ],
        ),
    ]
