# Generated by Django 3.0.3 on 2020-03-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200304_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phoneNo',
        ),
    ]
